/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Form.Home;
import Event.EventMenuSelected;
import Form.Form_Request;
import Form.Form_LeaveStatus;
import Form.RequestChange;
import Model.User;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;


public class SecurityStaff extends javax.swing.JFrame {

    /**
     * Creates new form SecurityStaff
     */
    private Home home;
    private Form_Request request;
    private Form_LeaveStatus status;
    private User user;
//

    public void setValue(User User) throws ParseException {
        this.user = User;
        menu.setValue(user);
        home.setValue(user);
        request.setValue(user);
        status.setValue(user);
        home.setLeavetaken(status.getNumApproved());
        request.setNumApproved(status.getNumApproved());
        home.refreshUI();
        
    }
//

    public SecurityStaff() throws ParseException {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        home = new Home();
        request = new Form_Request();
        status = new Form_LeaveStatus();
        menu.initMoving(SecurityStaff.this);
        menu.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void selected(int index) {
                if (index == 0) {

                    try {
                        setForm(home);
                        home.setLeavetaken(status.getNumApproved());
                        home.refreshUI();
                    } catch (ParseException ex) {
                        Logger.getLogger(SecurityStaff.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if (index == 1) {
                    setForm(request);
                    request.setNumApproved(status.getNumApproved());
                } else if (index == 2) {
                    try {
                        setForm(status);
                        status.refresh();
                    } catch (ParseException ex) {
                        Logger.getLogger(SecurityStaff.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if (index == 3) {
                    dispose();
                    Login lg = new Login();
                    lg.setVisible(true);
                    
                }

            }

        });
//        //  set when system open start with home form
        setForm(home);

//
    }

    private void setForm(JComponent com) {
        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new Swing.PanelBorder();
        menu = new Swing.Menu();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder1.setBackground(new java.awt.Color(215, 244, 255));
        panelBorder1.setForeground(new java.awt.Color(255, 232, 214));
        panelBorder1.setOpaque(true);
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelBorder1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, -1, 610));

        mainPanel.setBackground(new java.awt.Color(255, 232, 214));
        mainPanel.setForeground(new java.awt.Color(255, 232, 214));
        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.BorderLayout());
        panelBorder1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 0, 796, 603));

        getContentPane().add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecurityStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecurityStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecurityStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecurityStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    new SecurityStaff().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(SecurityStaff.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private Swing.Menu menu;
    private Swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
