/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Model.Request;
import Model.RequestType;
import Model.User;
import Utils.RequestDAO;
import Utils.User_Manager;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class RequestChange extends javax.swing.JFrame {

    private Map<String, List<Request>> listRequest = RequestDAO.readRequestListAsChar();

    /**
     * Creates new form RequestChange
     */
    public User user;

    public RequestChange() {
        initComponents();
        txtNumber.setBackground(Color.WHITE);

    }

    public void setValue(User User) {
        this.user = User;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        startDate = new com.raven.datechooser.DateChooser();
        endDate = new com.raven.datechooser.DateChooser();
        panelBorder1 = new Swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumber = new Model.TFUse();
        jLabel5 = new javax.swing.JLabel();
        txtendDateUpdate = new Model.TFUse();
        jLabel7 = new javax.swing.JLabel();
        cbLeaveUpdate = new javax.swing.JCheckBox();
        cbOverdutiesUpdate = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtreasonUpdate = new Model.TFUse();
        buttonEnd = new javax.swing.JButton();
        buttonStart = new javax.swing.JButton();
        applyBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtstartDateUpdate = new Model.TFUse();

        startDate.setDateFormat("yyyy-MM-dd");
        startDate.setTextRefernce(txtstartDateUpdate);

        endDate.setDateFormat("yyyy-MM-dd");
        endDate.setTextRefernce(txtendDateUpdate);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBorder1.setBackground(new java.awt.Color(252, 252, 252));
        panelBorder1.setOpaque(true);
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(46, 175, 232));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panelBorder1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 36));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(54, 189, 248));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHANGE REQUEST INFORMATION");
        panelBorder1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 560, 39));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("No.");
        panelBorder1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 40, 40));

        txtNumber.setEditable(false);
        txtNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtNumber.setForeground(new java.awt.Color(51, 51, 51));
        txtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberActionPerformed(evt);
            }
        });
        panelBorder1.add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 70, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("End Date");
        panelBorder1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 52, 22));

        txtendDateUpdate.setBackground(new java.awt.Color(255, 255, 255));
        txtendDateUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtendDateUpdateActionPerformed(evt);
            }
        });
        panelBorder1.add(txtendDateUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 220, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Type of Request");
        panelBorder1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, 22));

        cbLeaveUpdate.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cbLeaveUpdate);
        cbLeaveUpdate.setForeground(new java.awt.Color(51, 51, 51));
        cbLeaveUpdate.setText("Leave");
        cbLeaveUpdate.setBorder(null);
        cbLeaveUpdate.setOpaque(true);
        cbLeaveUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbLeaveUpdateMouseClicked(evt);
            }
        });
        cbLeaveUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLeaveUpdateActionPerformed(evt);
            }
        });
        panelBorder1.add(cbLeaveUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        cbOverdutiesUpdate.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cbOverdutiesUpdate);
        cbOverdutiesUpdate.setForeground(new java.awt.Color(51, 51, 51));
        cbOverdutiesUpdate.setText("Overduties");
        cbOverdutiesUpdate.setBorder(null);
        cbOverdutiesUpdate.setOpaque(true);
        cbOverdutiesUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbOverdutiesUpdateMouseClicked(evt);
            }
        });
        cbOverdutiesUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOverdutiesUpdateActionPerformed(evt);
            }
        });
        panelBorder1.add(cbOverdutiesUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Reason");
        panelBorder1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, 22));

        txtreasonUpdate.setBackground(new java.awt.Color(255, 255, 255));
        txtreasonUpdate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtreasonUpdate.setToolTipText("");
        panelBorder1.add(txtreasonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 220, 67));

        buttonEnd.setBackground(new java.awt.Color(208, 232, 247));
        buttonEnd.setForeground(new java.awt.Color(51, 51, 51));
        buttonEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-calendar-20.png"))); // NOI18N
        buttonEnd.setBorder(null);
        buttonEnd.setOpaque(true);
        buttonEnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEndMouseClicked(evt);
            }
        });
        buttonEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEndActionPerformed(evt);
            }
        });
        panelBorder1.add(buttonEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 40, 40));

        buttonStart.setBackground(new java.awt.Color(208, 232, 247));
        buttonStart.setForeground(new java.awt.Color(51, 51, 51));
        buttonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-calendar-20.png"))); // NOI18N
        buttonStart.setBorder(null);
        buttonStart.setOpaque(true);
        buttonStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonStartMouseClicked(evt);
            }
        });
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });
        panelBorder1.add(buttonStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 40, 40));

        applyBtn.setBackground(new java.awt.Color(208, 232, 247));
        applyBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        applyBtn.setForeground(java.awt.Color.black);
        applyBtn.setText("Update");
        applyBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(208, 232, 247), 3, true));
        applyBtn.setOpaque(true);
        applyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtnActionPerformed(evt);
            }
        });
        panelBorder1.add(applyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 100, 40));

        resetBtn.setBackground(new java.awt.Color(255, 255, 255));
        resetBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(76, 182, 208));
        resetBtn.setText("Reset");
        resetBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 182, 208), 3, true));
        resetBtn.setOpaque(true);
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        panelBorder1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 90, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Start Date");
        panelBorder1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, 30));

        txtstartDateUpdate.setBackground(new java.awt.Color(255, 255, 255));
        txtstartDateUpdate.setForeground(new java.awt.Color(51, 51, 51));
        txtstartDateUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstartDateUpdateActionPerformed(evt);
            }
        });
        panelBorder1.add(txtstartDateUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 220, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(560, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtendDateUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtendDateUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtendDateUpdateActionPerformed

    private void cbLeaveUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbLeaveUpdateMouseClicked
        // TODO add your handling code here:
        buttonEnd.setEnabled(true);
    }//GEN-LAST:event_cbLeaveUpdateMouseClicked

    private void cbLeaveUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLeaveUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLeaveUpdateActionPerformed

    private void cbOverdutiesUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbOverdutiesUpdateMouseClicked
        String startdate = txtstartDateUpdate.getText();
        txtendDateUpdate.setText(startdate);
        txtendDateUpdate.setEditable(false);
        txtendDateUpdate.setEnabled(false);
        buttonEnd.setEnabled(false);
    }//GEN-LAST:event_cbOverdutiesUpdateMouseClicked

    private void cbOverdutiesUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOverdutiesUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOverdutiesUpdateActionPerformed

    private void buttonEndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEndMouseClicked

    }//GEN-LAST:event_buttonEndMouseClicked

    private void buttonEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEndActionPerformed
        // TODO add your handling code here:
        endDate.showPopup();
    }//GEN-LAST:event_buttonEndActionPerformed

    private void buttonStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStartMouseClicked
        startDate.showPopup();
    }//GEN-LAST:event_buttonStartMouseClicked

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonStartActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberActionPerformed

    private void applyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyBtnActionPerformed

        int num = Integer.parseInt(txtNumber.getText());
        String startdate = txtstartDateUpdate.getText();
        String enddate = txtendDateUpdate.getText();
        LocalDate start = LocalDate.parse(startdate);
        LocalDate end = LocalDate.parse(enddate);
        String reason = txtreasonUpdate.getText();
        RequestType requestType = null;
        if (!check(start, end, num)) {
            JOptionPane.showMessageDialog(this, "You already have request this day", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (start.isBefore(LocalDate.now()) || startdate.equals(LocalDate.now())) {
            JOptionPane.showMessageDialog(this, "Start date cannot be before today", "Message", JOptionPane.ERROR_MESSAGE);
            txtstartDateUpdate.setText(LocalDate.now().toString());
        } else if (end.isBefore(start)) {
            JOptionPane.showMessageDialog(this, "End date cannot be before the start date", "Message", JOptionPane.ERROR_MESSAGE);
            txtendDateUpdate.setText(txtstartDateUpdate.getText());
        } else if (reason.equals("")) {
            JOptionPane.showMessageDialog(this, "Please type your reason", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (cbOverdutiesUpdate.isSelected() && start.getDayOfWeek() != DayOfWeek.SUNDAY) {
            JOptionPane.showMessageDialog(this, "The date you choose is not sunday, please choose again", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (!cbLeaveUpdate.isSelected() && !cbOverdutiesUpdate.isSelected()) {
            JOptionPane.showMessageDialog(this, "Choose your request type", "Message", JOptionPane.ERROR_MESSAGE);
        } else {
            if (cbLeaveUpdate.isSelected()) {
                requestType = RequestType.LEAVE;

            } else if (cbOverdutiesUpdate.isSelected()) {
                requestType = RequestType.OVERDUTIES;
            }
            Request requestForm = new Request(start, end, requestType, reason);
            try {
                User_Manager.editRequest(num - 1, user.getID(), requestForm);
                JOptionPane.showMessageDialog(this, "Change succesful", "Message", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(RequestChange.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_applyBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        txtstartDateUpdate.setText(LocalDate.now().plusDays(1).toString());
        txtendDateUpdate.setText(LocalDate.now().plusDays(1).toString());
        cbLeaveUpdate.setSelected(false);
        cbOverdutiesUpdate.setSelected(false);
        txtreasonUpdate.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    private void txtstartDateUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstartDateUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstartDateUpdateActionPerformed
    public boolean check(LocalDate start, LocalDate end, int num) {
        List<Request> list = listRequest.get(user.getID());
        for (int i = 0; i < num - 1; i++) {

            if (start.equals(list.get(i).getDateFrom()) || start.equals(list.get(i).getDateTo()) || end.equals(list.get(i).getDateTo())
                    || end.equals(list.get(i).getDateFrom())) {

                return false;
            }

        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyBtn;
    private javax.swing.JButton buttonEnd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonStart;
    public javax.swing.JCheckBox cbLeaveUpdate;
    public javax.swing.JCheckBox cbOverdutiesUpdate;
    private com.raven.datechooser.DateChooser endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private Swing.PanelBorder panelBorder1;
    private javax.swing.JButton resetBtn;
    private com.raven.datechooser.DateChooser startDate;
    public Model.TFUse txtNumber;
    public Model.TFUse txtendDateUpdate;
    public Model.TFUse txtreasonUpdate;
    public Model.TFUse txtstartDateUpdate;
    // End of variables declaration//GEN-END:variables
}
