/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import Model.User;
import Utils.User_Manager;
import com.raven.model.StatusType;
import com.raven.swing.ScrollBar;
import java.awt.Color;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author RAVEN
 */
public class Form_1 extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public Form_1() {
        initComponents();
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        List<User> listStaff = User_Manager.getListStaff();
        for (User user : listStaff) {
            table.addRow(new Object[]{user.getID(), user.getName(), user.getEmail(), user.getVerifyCode(), StatusType.APPROVED});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();
        jLabel2 = new javax.swing.JLabel();
        searchRequest_TF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 242, 242));

        spTable.setBorder(null);

        table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Verify Code", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(204, 204, 204));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        spTable.setViewportView(table);

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-staff-64.png"))); // NOI18N
        jLabel2.setText("ALL SECURITY STAFF");

        searchRequest_TF.setBackground(new java.awt.Color(255, 255, 255));
        searchRequest_TF.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        searchRequest_TF.setForeground(new java.awt.Color(0, 0, 51));
        searchRequest_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchRequest_TFKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Seach :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(135, 135, 135)
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(searchRequest_TF)))
                .addGap(0, 130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(searchRequest_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int selectedRow = table.getSelectedRow();
            Object cellValue = table.getValueAt(selectedRow, 0); // Assuming the first column index is 0
            if (cellValue != null) {
                ViewDuty editFrame = new ViewDuty();
                editFrame.setValue(cellValue.toString());
                editFrame.setVisible(true);
            }
        }
    }//GEN-LAST:event_tableMouseClicked

    private void searchRequest_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchRequest_TFKeyReleased
        // TODO add your handling code here:
        //         BookTableModel obj = (BookTableModel) bookTable.getModel();
        //        TableRowSorter<BookTableModel> tableRowSort = new TableRowSorter<>(obj);
        //        bookTable.setRowSorter(tableRowSort);BookTableModel
        //        tableRowSort.setRowFilter(RowFilter.regexFilter(searchBook_TF.getText()));

        String searchText = searchRequest_TF.getText().toLowerCase();

        // Create a TableRowSorter and set it on the table
        TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new TableRowSorter<>(
            (javax.swing.table.DefaultTableModel) table.getModel());
        table.setRowSorter(sorter);

        // Set the row filter based on the search text
        RowFilter<javax.swing.table.DefaultTableModel, Object> filter = RowFilter.regexFilter("(?i)" + searchText, 0, 1, 2, 3);
        sorter.setRowFilter(filter);
    }//GEN-LAST:event_searchRequest_TFKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField searchRequest_TF;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
