/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.form;

import Model.ApproveColumnRenderer;
import Model.Duty;
import Model.Place;
import Model.Request;
import Model.RequestTableModel;
import Model.RequestType;
import Model.StatusType;
import Model.User;
import Utils.User_Manager;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author Asus
 */
public class ViewRequest extends javax.swing.JFrame {
    
    private User user;
    private RequestTableModel requestTableModel;

    /**
     * Creates new form ViewRequest
     */
    public void setValue(String UserID) {
        this.user = User_Manager.findUser_byID(UserID);
        RequestTableModel model = new RequestTableModel();
        model.setValue(UserID);
        this.table.setModel(model);
        this.table.getColumnModel().getColumn(4).setCellRenderer(new ApproveColumnRenderer());
        this.staffName_TF.setText(this.user.getName());
        this.id_TF.setText(UserID);
        
    }
    
    public ViewRequest() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.staffName_TF.setEditable(false);
        this.id_TF.setEditable(false);
        this.setBackground(Color.blue);
        this.pack();
        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        staffName_TF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_TF = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        close_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/policeman.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 34, -1));

        staffName_TF.setBackground(new java.awt.Color(0, 0, 51));
        staffName_TF.setForeground(new java.awt.Color(255, 255, 255));
        staffName_TF.setBorder(null);
        getContentPane().add(staffName_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 180, 26));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/security.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("STAFF REQUEST");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 210, -1));

        id_TF.setBackground(new java.awt.Color(0, 0, 51));
        id_TF.setForeground(new java.awt.Color(255, 255, 255));
        id_TF.setBorder(null);
        getContentPane().add(id_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 320, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close_btn.setBackground(new java.awt.Color(0, 153, 153));
        close_btn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        close_btn.setForeground(new java.awt.Color(255, 255, 255));
        close_btn.setText("CLOSE");
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        jPanel1.add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        table.setBackground(new java.awt.Color(0, 0, 51));
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 630, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 2) {
            int selectedRow = table.getSelectedRow();
            Object cellValue1 = table.getValueAt(selectedRow, 0); // Assuming the first column index is 0
            Object cellValue2 = table.getValueAt(selectedRow, 1); // Assuming the first column index is 0
            Object cellValue3 = table.getValueAt(selectedRow, 2); // Assuming the first column index is 0
            Object cellValue4 = table.getValueAt(selectedRow, 3); // Assuming the first column index is 0
            Object cellValue5 = table.getValueAt(selectedRow, 4); // Assuming the first column index is 0  
            if (cellValue1 != null && cellValue2 != null && cellValue3 != null && cellValue4 != null) {
                Request curentRequest = new Request(LocalDate.parse(cellValue1.toString()),
                        LocalDate.parse(cellValue2.toString()), RequestType.valueOf(cellValue3.toString()), cellValue4.toString());
                Edit_request editRequestFrame = new Edit_request();
                editRequestFrame.setValue(this.user, curentRequest);
                System.out.println("date first column " + cellValue1.toString());
                
                editRequestFrame.setVisible(true);
                RequestTableModel newModel = new RequestTableModel();
                newModel.setValue(this.user.getID());
                this.table.setModel(newModel);
            } else {
                System.out.println("null cell value");
            }
        }
    }//GEN-LAST:event_tableMouseClicked

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_btn;
    private javax.swing.JTextField id_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField staffName_TF;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
