/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.StaffDutyTableModel;
import Model.User;
import Utils.User_Manager;
import com.raven.main.ManagerDashboard;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.BorderFactory;
import javax.swing.JFrame;

/**
 *
 * @author Asus
 */
public class ViewDuty extends javax.swing.JFrame {

    private StaffDutyTableModel staffTableModel;
    private User user;

    /**
     * Creates new form ViewDuty
     */
    public void setValue(String UserID) {
        this.user = User_Manager.findUser_byID(UserID);
        StaffDutyTableModel model = new StaffDutyTableModel();
        this.staffTableModel = model;
        this.staffTableModel.setValue(UserID);
        this.staffDutyTable.setModel(staffTableModel);
        this.setLocationRelativeTo(null);
        this.userName_TF.setText(this.user.getName());
        this.userName_TF.setEditable(false);
        this.id_TF.setText(this.user.getID());
        this.id_TF.setEditable(false);
        this.email_TF.setText(this.user.getEmail());
        this.email_TF.setEditable(false);
        this.verifyCode_TF.setText(this.user.getVerifyCode());
        this.verifyCode_TF.setEditable(false);

    }

    public ViewDuty() {
        initComponents();
        this.pack();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffDutyTable = new javax.swing.JTable();
        id_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        verifyCode_label = new javax.swing.JLabel();
        id_TF = new javax.swing.JTextField();
        email_TF = new javax.swing.JTextField();
        verifyCode_TF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        user_icon = new javax.swing.JLabel();
        userName_TF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        close_button = new javax.swing.JButton();
        refresh_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Verify Code", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        spTable.setViewportView(table);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staffDutyTable.setBackground(new java.awt.Color(0, 0, 51));
        staffDutyTable.setForeground(new java.awt.Color(255, 255, 255));
        staffDutyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        staffDutyTable.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        staffDutyTable.setGridColor(new java.awt.Color(0, 0, 51));
        staffDutyTable.setSelectionBackground(new java.awt.Color(204, 255, 255));
        staffDutyTable.setSelectionForeground(new java.awt.Color(51, 51, 55));
        staffDutyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffDutyTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(staffDutyTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 520, 160));

        id_label.setBackground(new java.awt.Color(51, 51, 51));
        id_label.setForeground(new java.awt.Color(255, 255, 255));
        id_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id_label.setText("ID");
        getContentPane().add(id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, -1));

        email_label.setForeground(new java.awt.Color(255, 255, 255));
        email_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email_label.setText("Email");
        getContentPane().add(email_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, -1));

        verifyCode_label.setForeground(new java.awt.Color(255, 255, 255));
        verifyCode_label.setText("Verify Code");
        getContentPane().add(verifyCode_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));
        getContentPane().add(id_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 160, -1));
        getContentPane().add(email_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 160, -1));
        getContentPane().add(verifyCode_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 160, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(0, 0, 51));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/8.png"))); // NOI18N
        panel.add(user_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 70, 40));

        userName_TF.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        userName_TF.setForeground(new java.awt.Color(0, 0, 102));
        userName_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userName_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName_TFActionPerformed(evt);
            }
        });
        panel.add(userName_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, 30));

        jPanel2.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 450));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close_button.setBackground(new java.awt.Color(0, 153, 153));
        close_button.setText("Close");
        close_button.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });
        jPanel4.add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 80, -1));

        refresh_Button.setBackground(new java.awt.Color(0, 0, 51));
        refresh_Button.setForeground(new java.awt.Color(255, 255, 255));
        refresh_Button.setText("Refresh");
        refresh_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        refresh_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(refresh_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("STAFF DUTY SCHEDULE");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 550, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tableMouseClicked

    private void refresh_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_ButtonActionPerformed
        // TODO add your handling code here:
        this.staffTableModel = (new StaffDutyTableModel());
        this.staffTableModel.setValue(this.id_TF.getText());
        this.staffDutyTable.setModel(staffTableModel);

    }//GEN-LAST:event_refresh_ButtonActionPerformed

    private void staffDutyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffDutyTableMouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 2) {
            int selectedRow = staffDutyTable.getSelectedRow();
            Object cellValue = staffDutyTable.getValueAt(selectedRow, 0); // Assuming the first column index is 0
            Object cellValue3 = staffDutyTable.getValueAt(selectedRow, 1); // Assuming the first column index is 0
            Object cellValue1 = staffDutyTable.getValueAt(selectedRow, 2); // Assuming the first column index is 0
            Object cellValue2 = staffDutyTable.getValueAt(selectedRow, 3); // Assuming the first column index is 0

            if (cellValue != null) {
                Edit_Duty newdutyFrame = new Edit_Duty();
                newdutyFrame.setValue(cellValue.toString(), cellValue1.toString(), cellValue2.toString(),cellValue3.toString(), this.user);
                System.out.println("date first column " + cellValue.toString());
                newdutyFrame.setVisible(true);
            } else {
                System.out.println("null cell value");
            }
        }
    }//GEN-LAST:event_staffDutyTableMouseClicked

    private void userName_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userName_TFActionPerformed

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDuty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDuty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDuty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDuty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_button;
    private javax.swing.JTextField email_TF;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField id_TF;
    private javax.swing.JLabel id_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JButton refresh_Button;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JTable staffDutyTable;
    private com.raven.swing.Table table;
    private javax.swing.JTextField userName_TF;
    private javax.swing.JLabel user_icon;
    private javax.swing.JTextField verifyCode_TF;
    private javax.swing.JLabel verifyCode_label;
    // End of variables declaration//GEN-END:variables
}
